Match specifically on event.git.sha
We were presented with an example where CLI invocation errored with:

```
rwx run --file .rwx/ci.yml --target test --wait
Error: unable to resolve CLI init params: multiple event triggers use different init param names for event.git.sha
```

The config looked like:

```
on:
  github:
    push:
      commit-sha: ${{ event.git.sha }}
      docker-tag: rwx-${{ event.git.sha }}
  cli:
    commit-sha: ${{ event.git.sha }}
    docker-tag: false
```

We should have never even reached into the push trigger to try to
resolve the correct git init param. There's already a unit test meant to
enforce this:

https://github.com/rwx-cloud/rwx/blob/f49aad2d4077da411716d1200a1b48cc28409034/internal/cli/service_resolve_cli_params_test.go#L75

But the test was too narrow because it wasn't possible to trigger the
error message with only a single other trigger type (there's nothing for
it to conflict with).

This adds a few more unit tests to further constrain behavior. And makes
two functional changes:

1. We now correctly short circuit early
2. We _only_ consider it a git param if `${{ event.git.sha }}` isn't
   interpolated into a larger string. Since the whole purpose of this it
   to best-effort detect which init param will get passed into
   git/clone.